### ISSUE TITLE
Noise cancellation method

### ISSUE THREAD

**Issue by seccolf** [seccolf/mcal_sim_test#3] opened 2022-02-22 19:48 UTC
We seem to find biases when not using the noise cancellation technique in the sims (ie. generating a pair of +g1 and -g1 sims and computing differences between the images).

That technique should not be clearing up a bias, but rather only affecting the error bars.

**Comment by DhayaaAnbajagane** [comment] 2022-08-12 07:08
Fixed. Was being caused by not actually setting the 2**30 edge bitmask that is necessary, and was due to edge case in medsmaker code. [Code was updated to fix this](https://github.com/esheldon/meds/commit/0de1205036f2f0c0defe9e1d40a79ebacbec3088). Noise cancellation technique is also updated and [fixed now](https://github.com/seccolf/mcal_sim_test/commit/d528cfb802634b8c111630ddca079f039a9c7fec).

**Closed as completed by DhayaaAnbajagane** 2022-08-12 07:08 UTC
